### PR TITLE
Get list of python versions from online repo when creating environment

### PR DESCRIPTION
**Pull request by titus-ong**
Previously, there were only the options of Python 2.7, 3.5, 3.6 and 3.7 when creating a new conda environment. This update removes that fixed list and gets an updated list from the online conda repo so the latest Python versions are available.

This should detect the platform properly (Windows, Linux or OSX) and download the 32-bit Python binary by default. I've included an `architecture` option in the settings so users can download the 64-bit version if required. I also included a `dependencies.json` for the `requests` module to retrieve the repo URL.

Please let me know if there's anything I can change/improve on.

### CODE REVIEW

**Comment by mandeep** [comment]
@titus-ong thanks this looks great! I'll try it out and let you know how it goes. One thing I think that needs to be changed is that `architecture` should default to 64 instead of 32.

**Comment by titus-ong** [comment]
@mandeep cool, I've changed it to be 64 by default. May I know why though? I must admit I am not familiar with these things but I thought Python is 32bit by default when downloaded (at least for Windows), so I thought it made more sense for 32 to be the default.

**Comment by mandeep** [comment]
The architecture field is for the architecture of the system. Most systems are 64bit.  I think Anaconda provides 32bit builds for Linux and Windows, but I will need to double check.

**Comment by mandeep** [comment]
@titus-ong I was able to test this out and it appears everything works amazingly. Thanks so much for your contribution!

**Pull request merged**
